# Generated by Django 4.2.30 on 2026-05-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentexpirationnotification_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentexpirationnotification',
            name='event_type',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('upcoming_urgent', 'Upcoming urgent'), ('expired', 'Expired')], max_length=20),
        ),
    ]
