# Generated by Django 4.2.30 on 2026-05-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_caseprogressstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('DESISTIMIENTO_TACITO', 'DESISTIMIENTO TÁCITO DEL USUARIO'), ('DESISTIMIENTO_EXPRESO', 'DESISTIMIENTO EXPRESO DEL USUARIO'), ('FINALIZADO_GANADO', 'CASO FINALIZADO JURÍDICAMENTE (GANADO)'), ('FINALIZADO_PERDIDO', 'CASO FINALIZADO JURÍDICAMENTE (PERDIDO)'), ('INFRINGIO_TERMINOS', 'INFRINGIÓ LOS TÉRMINOS DEL CONSULTORIO JURÍDICO'), ('OTRO', 'OTRO')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='cancellation_reason_other',
            field=models.TextField(blank=True, null=True),
        ),
    ]
