# Generated by Django 4.2.30 on 2026-05-24 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_case_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='subclinic',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subclinics', to='cases.category'),
        ),
        migrations.AlterField(
            model_name='subclinic',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='subclinic',
            unique_together={('name', 'category')},
        ),
    ]
